font_family      JetBrainsMono NFM Light
font_size        12.0

bold_font        JetBrainsMono NFM Bold
italic_font      JetBrainsMono NFM Italic
bold_italic_font JetBrainsMono NFM Bold Italic


# BEGIN_KITTY_THEME
# Ghostty Default
include current-theme.conf
# END_KITTY_THEME

# вкладки сверху, со «скошенными» разделителями
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
# показывать панель даже с одной вкладкой
tab_bar_min_tabs        1          

# воздух вокруг текста
window_padding_width    8

# лёгкая прозрачность (по вкусу)
background_opacity      0.8

# заголовок вкладки: номер + имя процесса
tab_title_template      "{index}: {title}"

cursor_blink_interval   0.5
