# Theme -- Ghostty Default
include current-theme.conf

# Fonts
font_family             JetBrainsMono NFM Light
font_size               12.0

bold_font               JetBrainsMono NFM Bold
italic_font             JetBrainsMono NFM Italic
bold_italic_font        JetBrainsMono NFM Bold Italic

# Window
hide_window_decorations yes
window_padding_width    8
background_opacity      0.8

# Tabs
tab_title_template      "{index}: {title}"
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_min_tabs        1          

# Cursor, mouse
cursor_shape            beam
cursor_blink_interval   0.5
cursor_trail 3
copy_on_select          clipboard

# Urls
url_style               curly
detect_urls             yes
open_url_with           default

# Mappings
map ctrl+shift+t       new_tab_with_cwd
map ctrl+shift+enter   new_window_with_cwd
map ctrl+shift+o       launch --location=hsplit --cwd=current
map ctrl+shift+e       launch --location=vsplit --cwd=current
